version: "3.9"
networks:
  dev-network:
services:
  web:
    cap_add:
      - NET_ADMIN
    build:
      context: .
      dockerfile: ./web.Dockerfile
      dockerfile: ./dev.Dockerfile
    environment:
      DATABASE_URL: postgresql://admin:P@55w0rd@postgres:5432/meteo?sslmode=disable
    ports:
      - "80:80"
    command: "go run ./cmd/web start"
    volumes:
      - ./:/app/
    networks:
      - dev-network
  proxy:
    cap_add:
      - ALL
    build:
      context: .
      dockerfile: ./proxy.Dockerfile
      dockerfile: ./dev.Dockerfile
    environment:
      DATABASE_URL: postgresql://admin:P@55w0rd@postgres:5432/meteo?sslmode=disable
    privileged: true
    ports:
      - "53:53"
    command: "go run ./cmd/proxy start"
    volumes:
      - ./:/app/
    networks:
      hostnet: {}
    networks:
     - dev-network
  postgres:
    image: postgres:14.5
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=P@55w0rd
      - POSTGRES_USER=admin
      - POSTGRES_DB=meteo
    networks:
     - dev-network
  freeradius:
    image: freeradius/freeradius-server:3.0.26-alpine
    ports:
      - "1812-1813:1812-1813"
    networks:
     - dev-network
networks:
  dev-network:
   external: true
  hostnet:
    external: true
    name: host