version: "3.9"
networks:
  dev-network:
services:
  web:
    depends_on:
      - postgres
    cap_add:
      - NET_ADMIN
    build:
      context: .
      dockerfile: ./docker/web/dev.Dockerfile
    environment:
      - DATABASE_URL=${DB_WEB_URL}
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - WEB_HOST=${WEB_HOST}
      - WEB_PORT=${WEB_PORT}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    command: "go run ./cmd/web start"
    volumes:
      - ./:/app/
    networks:
      - dev-network
  proxy:
    depends_on:
      - postgres
      - web
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    build:
      context: .
      dockerfile: ./docker/proxy/dev.Dockerfile
    environment:
      - DATABASE_URL=${DB_PROXY_URL}
    command: "go run ./cmd/proxy start"
    volumes:
      - ./:/app/
  xu4:
    depends_on:
      - postgres
    hostname: xu4
    cap_add:
      - ALL
    network_mode: "host"
    privileged: true
    build:
      context: .
      dockerfile: ./docker/xu4/dev.Dockerfile
    environment:
      - DATABASE_URL=${DB_XU4_URL}
    command: "go run ./cmd/xu4 start"
    volumes:
      - ./:/app/
  postgres:
    image: postgres:14.5
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
     - dev-network
