version: "3.9"
networks:
  dev-network:
services:
  web:
    cap_add:
      - NET_ADMIN
    build:
      context: .
      dockerfile: ./web.Dockerfile
      dockerfile: ./dev.Dockerfile
    environment:
      DATABASE_URL: postgresql://admin:P@55w0rd@postgres:5432/meteo?sslmode=disable
    ports:
      - "80:80"
    command: "go run ./cmd/web start"
    volumes:
      - ./:/app/
    networks:
      - dev-network
  proxy:
#    privileged: true
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    build:
      context: .
      dockerfile: ./proxy.Dockerfile
      dockerfile: ./dev.Dockerfile
    environment:
      DATABASE_URL: postgresql://admin:P@55w0rd@127.0.0.1:5432/meteo?sslmode=disable
#      DATABASE_URL: postgresql://admin:P@55w0rd@postgres:5432/meteo?sslmode=disable
    ports:
      - "53:53"
    command: "go run ./cmd/proxy start"
    volumes:
      - ./:/app/
#    networks:
#      - dev-network
  postgres:
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=P@55w0rd
      - POSTGRES_USER=admin
      - POSTGRES_DB=meteo
    networks:
     - dev-network
  freeradius:
    image: freeradius/freeradius-server:3.0.26-alpine
    ports:
      - "1812-1813:1812-1813"
    networks:
     - dev-network
