version: "3.9"

networks:
  app-network:
services:
  server:
    build:
      context: .
      dockerfile: ./web.Dockerfile
    environment:
      - DATABASE_URL=${DB_WEB_URL}
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres:14.5
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - app-network