version: "3.9"

networks:
  app-network:
services:
  server:
    build:
      context: .
      dockerfile: ./web.Dockerfile
    environment:
      DATABASE_URL: postgresql://admin:P@55w0rd@postgres:5432/meteo?sslmode=disable
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres:14.5
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=P@55w0rd
      - POSTGRES_USER=admin
      - POSTGRES_DB=meteo
    networks:
      - app-network