version: "3.9"
services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "meteo"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "P@55w0rd"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
