######################
# User settings #

# insert here user settings

########################
# Applicaton settings #
app:
  version: 1  # api version
  master: true
  dir: /var/tmp # work dir

########################
# Cluster settings #
cluster:
  bind: 127.0.0.1
  port: 10000
  interface: eth0
  virtual: 192.168.1.10

########################
# Client settings #
client:
  ssl: true
  local: 192.168.1.8
  remote: 192.168.1.7
  crt: ./certs/client.crt
  key: ./certs/client.key

########################
# Auth settings #
auth:
  AccessTokenPrivateKeyPath: .certs/auth/access-private.pem
  AccessTokenPublicKeyPath: .certs/auth/access-public.pem
  RefreshTokenPrivateKeyPath: .certs/auth/refresh-private.pem
  RefreshTokenPublicKeyPath: .certs/auth/refresh-public.pem
  PassResetCodeExpiration:  15
  JwtExpiration: 5
  JwtKey: !488ieufhlUI070%5~
########################
# Web Server settings #
web:
  title: Web
  active: true
  ssl: true # true/false, if server has SSL certificate set to true to use HTTPS, false = HTTP
  listen: 0.0.0.0 # address on which application is running. Not localhost!
  port: 443 # port on which application is running
  ui: ./dist/spa #path to ui spa
  crt: ./certs/server.crt
  key: ./certs/server.key
  tls_min: TLS12

########################
# Dtabase settings #
database:
  url: postgresql://admin:P@55w0rd@127.0.0.1:5432/meteo?sslmode=disable
  pool:
    max: 50
  sync: false
  exclude:
    - ssh_hosts

########################
# Proxy settings #
proxy:
  title: Proxy
  active: false
  listen: 0.0.0.0
  udpPort: 53
  tcpPort: 53
  restBind: 0.0.0.0
  restPort: 11000
  restCrt: ./certs/server.crt
  restKey: ./certs/server.key
  metrics: false
  nsvpn:
    - dns.google:853@8.8.8.8
  nsdirect:
    - one.one.one.one:853@1.1.1.1
  nsprovider:
    - 82.209.200.16
    - 82.209.200.17
  resolvers:
    - 127.0.0.1
    - 192.168.1.5
  cached: true
  cachesize: 0
  unlocker: true
  updateInterval: 24h
  blockIPv4: 127.0.0.0
  blockIPv6: 0:0:0:0:0:0:0:0
  adblock: true
  adsources:
    - https://someonewhocares.org/hosts/zero/hosts
    - https://adaway.org/hosts.txt
    - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
    - https://cdn.jsdelivr.net/gh/evankrob/hosts-filenetrehost@master/ad_servers.txt
    - https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

########################
# XU4 settings #
xu4:
  title: XU4
  active: true
  bind: 0.0.0.0
  port: 15000
  crt: ./certs/server.crt
  key: ./certs/server.key

########################
# Messanger settings #
messanger:
  title: Messanger
  active: true
  bind: 0.0.0.0
  port: 14000
  crt: ./certs/server.crt
  key: ./certs/server.key
  telegramchatid: ${CHATID}
  telegramkey: ${KEY}
  telegramurl: https://api.telegram.org/bot

########################
# SSHCLIENT settings #
sshclient:
  title: SshClient
  active: true
  bind: 0.0.0.0
  port: 13000
  crt: ./certs/server.crt
  key: ./certs/server.key
  git:
    host: 192.168.1.1
    port: 2222
    user: vivask
    repository: Mikrotiks
    remote: origin
    commit: "initial commit"
  ppp:
    host: 192.168.1.1
    port: 22
    user: manager
    interface: ByFly
    script: ppp-restart
  mikrotik:
    hosts:
      - 192.168.1.1
      - 192.168.1.2
      - 192.168.1.3
      - 192.168.1.4
    ports:
      - 22
      - 22
      - 22
      - 22
    users:
      - ${USER1}
      - ${USER1}
      - ${USER1}
      - ${USER1}
    repository: /opt/www/git/Mikrotik
  vpn:
    host: 192.168.1.1
    port: 22
    user: ${USER}
    list: tovpn

########################
# SCHEDULE settings #
schedule:
  title: Schedule
  active: true
  bind: 0.0.0.0
  port: 12000
  crt: ./certs/server.crt
  key: ./certs/server.key
