######################
# User settings #

# insert here user settings

########################
# Applicaton settings #
app:
  version: 1  # api version
  master: false
  dir: /var/tmp # work dir

########################
# Cluster settings #
cluster:
  bind: 127.0.0.1
  port: 10000
  interface: eth0
  virtual: 192.168.1.9

########################
# Client settings #
client:
  ssl: false
  local: 127.0.0.1
  remote: 192.168.1.5
  ca: ./certs/MeteoCA.crt
  crt: ./certs/client.crt
  key: ./certs/client.key

########################
# Web Server settings #
web:
  title: Web
  active: true
  ssl: false # true/false, if server has SSL certificate set to true to use HTTPS, false = HTTP
  listen: 0.0.0.0 # address on which application is running. Not localhost!
  port: 80 # port on which application is running
  ui: ./dist/spa #path to ui spa
  ca: ./certs/MeteoCA.crt
  crt: ./certs/192.168.1.9.crt
  key: ./certs/192.168.1.9.key
  tls_min: TLS12

########################
# Dtabase settings #
database:
  url: postgresql://admin:P@55w0rd@localhost:5432/meteo?sslmode=disable
  pool:
    max: 50
  sync: false
  exclude:
    - ssh_hosts

########################
# Proxy settings #
proxy:
  title: Proxy
  active: true
  listen: 0.0.0.0
  udpPort: 53
  tcpPort: 53
  restBind: 127.0.0.1
  restPort: 11000
  metrics: false
  nsvpn:
    - dns.google:853@8.8.8.8
  nsdirect:
    - one.one.one.one:853@1.1.1.1
  nsprovider:
    - 82.209.200.16
    - 82.209.200.17
  resolvers:
    - 127.0.0.1
    - 192.168.1.5
  cached: true
  cachesize: 0
  unlocker: true
  updateInterval: 24h
  blockIPv4: 127.0.0.0
  blockIPv6: 0:0:0:0:0:0:0:0
  adblock: true
  adsources:
    - https://someonewhocares.org/hosts/zero/hosts
    - https://adaway.org/hosts.txt
    - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
    - https://cdn.jsdelivr.net/gh/evankrob/hosts-filenetrehost@master/ad_servers.txt
    - https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
