package database

import "github.com/gin-gonic/gin"

func (p databaseAPI) RegisterAPIV1(router *gin.RouterGroup) {
	database := router.Group("/database")
	database.PUT("/sync", p.SyncEsp32Tables)

	database.GET("/bmx280/notsync", p.GetNotSyncBmx280)
	database.GET("/bmx280", p.GetAllBmx280)
	database.POST("/bmx280", p.AddSyncBmx280)
	database.PUT("/lock/bmx280", p.LockBmx280)
	database.PUT("/unlock/bmx280", p.UnlockBmx280)
	database.PUT("/sync/bmx280", p.SyncBmx280)
	database.PUT("/replace/bmx280", p.ReplaceBmx280)

	database.GET("/ds18b20/notsync", p.GetNotSyncDs18b20)
	database.GET("/ds18b20", p.GetAllDs18b20)
	database.POST("/ds18b20", p.AddSyncDs18b20)
	database.PUT("/lock/ds18b20", p.LockDs18b20)
	database.PUT("/unlock/ds18b20", p.UnlockDs18b20)
	database.PUT("/sync/ds18b20", p.SyncDs18b20)
	database.PUT("/replace/ds18b20", p.ReplaceDs18b20)

	database.GET("/mics6814/notsync", p.GetNotSyncMics6814)
	database.GET("/mics6814", p.GetAllMics6814)
	database.POST("/mics6814", p.AddSyncMics6814)
	database.PUT("/lock/mics6814", p.LockMics6814)
	database.PUT("/unlock/mics6814", p.UnlockMics6814)
	database.PUT("/sync/mics6814", p.SyncMics6814)
	database.PUT("/replace/mics6814", p.ReplaceMics6814)

	database.GET("/ze08ch2o/notsync", p.GetNotSyncZe08ch2o)
	database.GET("/ze08ch2o", p.GetAllZe08ch2o)
	database.POST("/ze08ch2o", p.AddSyncZe08ch2o)
	database.PUT("/lock/ze08ch2o", p.LockZe08ch2o)
	database.PUT("/unlock/ze08ch2o", p.UnlockZe08ch2o)
	database.PUT("/sync/ze08ch2o", p.SyncZe08ch2o)
	database.PUT("/replace/ze08ch2o", p.ReplaceZe08ch2o)

	database.GET("/radsens/notsync", p.GetNotSyncRadsens)
	database.GET("/radsens", p.GetAllRadsens)
	database.POST("/radsens", p.AddSyncRadsens)
	database.PUT("/lock/radsens", p.LockRadsens)
	database.PUT("/unlock/radsens", p.UnlockRadsens)
	database.PUT("/sync/radsens", p.SyncRadsens)
	database.PUT("/replace/radsens", p.ReplaceRadsens)

	database.GET("/aht25/notsync", p.GetNotSyncAht25)
	database.GET("/aht25", p.GetAllAht25)
	database.POST("/aht25", p.AddSyncAht25)
	database.PUT("/lock/aht25", p.LockAht25)
	database.PUT("/unlock/aht25", p.UnlockAht25)
	database.PUT("/sync/aht25", p.SyncAht25)
	database.PUT("/replace/aht25", p.ReplaceAht25)

	database.GET("/ssh_keys", p.GetAllSshKeys)
	database.GET("/ssh_hosts", p.GetAllSshHosts)
	database.GET("/git_users", p.GetAllGitUsers)
	database.GET("/homezones", p.GetAllHomezones)
	database.GET("/tovpn_manuals", p.GetAllToVpnManual)
	database.GET("/tovpn_autos", p.GetAllToVpnAuto)
	database.GET("/tovpn_ignores", p.GetAllToVpnIgnore)
	database.GET("/tasks", p.GetAllTasks)
	database.GET("/jobs", p.GetAllJobs)
	database.GET("/radcheck", p.GetAllRadcheck)
	database.GET("/radverified", p.GetAllRadverified)
	database.GET("/users", p.GetAllUsers)

	database.PUT("/replace/ssh_keys", p.ReplaceSshKeys)
	database.PUT("/replace/ssh_hosts", p.ReplaceSshHosts)
	database.PUT("/replace/git_users", p.ReplaceGitUsers)
	database.PUT("/replace/homezones", p.ReplaceHomezone)
	database.PUT("/replace/tovpn_manuals", p.ReplaceToVpnManual)
	database.PUT("/replace/tovpn_autos", p.ReplaceToVpnAuto)
	database.PUT("/replace/tovpn_ignores", p.ReplaceToVpnIgnore)
	database.PUT("/replace/tasks", p.ReplaceTasks)
	database.PUT("/replace/jobs", p.ReplaceJobs)
	database.PUT("/replace/radcheck", p.ReplaceRadcheck)
	database.PUT("/replace/radverified", p.ReplaceRadverified)
	database.PUT("/replace/users", p.ReplaceUser)
}
